copy versionbay ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,10 +1,10 @@
-# This is a basic workflow to help you get started with Actions
+# This is a basic workflow to help you get started with MATLAB Actions
 
-name: CI
+name: MATLAB Test
 
-# Controls when the workflow will run
+# Controls when the action will run.
 on:
-  # Triggers the workflow on push or pull request events but only for the master branch
+  # Triggers the workflow on push or pull request events but only for the main branch
   push:
     branches: [ master ]
   pull_request:
@@ -13,24 +13,63 @@ on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
+
   # This workflow contains a single job called "build"
   build:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
+    continue-on-error: true
+
+    strategy:
+      matrix:
+        release: [R2020a, R2020b, R2021a, R2021b]
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
+      - name: Check out repository
+        uses: actions/checkout@v2
+        with:
+          submodules: true
+          lfs: true
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
+      # Sets up MATLAB on the GitHub Actions runner
+      - name: Setup MATLAB
+        uses: matlab-actions/setup-matlab@v1
+        with:
+          release: ${{ matrix.release }}
 
       # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+      - name: Run all tests
+        uses: matlab-actions/run-tests@v1
+        with:
+          test-results-junit: test-results/results_${{ matrix.release }}.xml
+          test-results-pdf: test-results/results_${{ matrix.release }}.pdf
+          source-folder: functions
+          select-by-folder: tests
+          code-coverage-cobertura: coverage_${{ matrix.release }}.xml
+
+      # Upload JUnit results to codecov.io
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v2
+        with:
+          file: coverage_${{ matrix.release }}.xml
+          flags: ${{ matrix.release }}
+
+      # Show Test Report
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: MATLAB Test ${{ matrix.release }}
+          path: test-results/results_${{ matrix.release }}.xml
+          reporter: java-junit
+
+      # Upload PDF artifacts
+      - name: Store test report
+        uses: actions/upload-artifact@v2
+        if: always()
+        with:
+          name: my-artifact-${{ matrix.release }}
+          path: test-results/results_${{ matrix.release }}.pdf
